version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.6
    steps:
      - checkout
      - run:
          name: "Set up environment"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: "Install Dependencies"
          command: |
            sudo apt-get update && sudo apt-get install subversion
            sudo -E docker-php-ext-install mysqli
            sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
            sudo apt-get update && sudo apt-get install mysql-client-5.7
      - run:
          name: "Run PHP tests"
          command: |
            composer install
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            composer test
          environment:
            WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
            WP_CORE_DIR: "/tmp/wordpress/"
      - run:
          name: "Run asset tests"
          command: |
            yarn
            yarn test
            yarn build
  deploy_plugin_staging:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c0:36:87:5e:a5:8f:b7:6e:62:d0:3e:3f:de:56:06:56"
      - run:
          name: "Build plugin"
          command: |
            yarn
            yarn build
            composer install --no-dev --optimize-autoloader
      - run: sudo apt-get install -y lftp
      - run: lftp -c 'set sftp:auto-confirm yes; set sftp:connect-program "ssh -p 22222 -a -x -i ~/.ssh/id_rsa"; connect sftp://'"$SFTP_USERNAME"':'"$SFTP_PASSWORD"'@'"$SFTP_HOSTNAME"' -e "mirror -v -R --exclude src/ --exclude bin/ --exclude tests/ --exclude .git/ --exclude .circleci/ --exclude node_modules/ ./ '"$WEB_ROOT_STAGING"'/wp-content/plugins/'"$PLUGIN_NAME"'; quit"'
  deploy_plugin_production:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c0:36:87:5e:a5:8f:b7:6e:62:d0:3e:3f:de:56:06:56"
      - run:
          name: "Build plugin"
          command: |
            yarn
            yarn build
            composer install --no-dev --optimize-autoloader
      - run: sudo apt-get install -y lftp
      - run: lftp -c 'set sftp:auto-confirm yes; set sftp:connect-program "ssh -p 22222 -a -x -i ~/.ssh/id_rsa"; connect sftp://'"$SFTP_USERNAME"':'"$SFTP_PASSWORD"'@'"$SFTP_HOSTNAME"' -e "mirror -v -R --exclude src/ --exclude bin/ --exclude tests/ --exclude .git/ --exclude .circleci/ --exclude node_modules/ ./ '"$WEB_ROOT_PRODUCTION"'/wp-content/plugins/'"$PLUGIN_NAME"'; quit"'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_plugin_staging:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy_plugin_production:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
